# Generated by Django 3.1.4 on 2020-12-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre corto'),
        ),
    ]
