# Generated by Django 3.1.4 on 2020-12-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_auto_20201218_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mi departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
