# Generated by Django 3.1.4 on 2020-12-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap', models.CharField(max_length=50)),
                ('am', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
